Update template manifest
apify/actor-templates pull request #121
Opened 2023-02-02 14:06 UTC by PerVillalva

2023-02-03 15:13 UTC, jbartadev reviewed
Hey Perci @PerVillalva, I updated the manifest with the new properties [we need](https://github.com/apify/apify-web/issues/2343) for the new template library in the console - I added `label`, `category`, and `technologies`. Because of these changes the descriptions still look quite poor and not very useful. Could someone from marketing do another iteration of these so it's usable the way it is presented in [the new design](https://www.figma.com/proto/oVEMTguG3LLMyHgw9YcroE/Creating-Actor---uplift?node-id=1330%3A78844&scaling=min-zoom&page-id=403%3A60&starting-point-node-id=1016%3A18446&show-proto-sidebar=1) we're currently working on?

2023-02-06 00:09 UTC, PerVillalva commented
@jbartadev Thanks for the updated structure! It does look more comprehensive and well-organized than before. I've made a few adjustments to the descriptions so they are similar to the new text we have in the console.

Please let me know if you think the descriptions are better now, and then I can ask Theo to proofread them to ensure everything is correct.

2023-02-06 08:08 UTC, mnmkng commented on templates/manifest.json
> +            "label": "Start wit Python",
```suggestion
            "label": "Start with Python",
```

2023-02-06 08:13 UTC, jbartadev requested changes
Thanks, Perci for the quick changes and reaction! I guess it's much better now. I just found small typos in the description. 🚀

Theo makes it perfect for sure, please let me know when is he going to be able to check it so we can move forward 😄

2023-02-06 08:13 UTC, jbartadev commented on templates/manifest.json
> +            "description": "Basic template for developing actors on the Apify platform. using TypeScript and Node.js.",
`using TypeScript and Node.js.` - the `Using` should have the capital letters as it is at the beginning of the sentence

```suggestion
            "description": "Basic template for developing actors on the Apify platform. Using TypeScript and Node.js.",
```

2023-02-06 08:13 UTC, jbartadev commented on templates/manifest.json
> +            "description": "Basic template for developing actors on the Apify platform. using Python.",
Same here - I'm also not sure if `Using python` sounds and looks good as a sentence 😸 
```suggestion
            "description": "Basic template for developing actors on the Apify platform. Using Python.",
```

2023-02-06 08:26 UTC, PerVillalva commented
@jbartadev  I will contact Theo today and ping you once he finishes the text's final proofreading.

2023-02-06 08:56 UTC, TheoVasilis requested changes

2023-02-06 08:56 UTC, TheoVasilis commented on templates/manifest.json
> +            "description": "Basic template for developing actors on the Apify platform. using JavaScript and Node.js.",
platform. using - remove .

2023-02-06 08:56 UTC, TheoVasilis commented on templates/manifest.json
> +            "description": "Basic template for developing actors on the Apify platform. Using TypeScript and Node.js.",
Basic template for developing actors on the Apify platform using TypeScript and Node.js.

2023-02-06 08:56 UTC, TheoVasilis commented on templates/manifest.json
> +            "description": "Standard and up to date template for developing with Crawlee's CheerioCrawler.",
Standard and up-to-date template for developing with Crawlee's CheerioCrawler.

2023-02-06 08:56 UTC, TheoVasilis commented on templates/manifest.json
> +            "description": "Standard and up to date template for developing with Crawlee's PuppeteerCrawler.",
Standard and up-to-date template for developing with Crawlee's PuppeteerCrawler.

2023-02-06 08:56 UTC, TheoVasilis commented on templates/manifest.json
> +            "description": "Standard and up to date template for developing with Crawlee's PlaywrightCrawler.",
Standard and up-to-date template for developing with Crawlee's PlaywrightCrawler.

2023-02-06 08:56 UTC, TheoVasilis commented on templates/manifest.json
> +            "description": "Standard and up to date template for developing with Crawlee's CheerioCrawler.",
Standard and up-to-date template for developing with Crawlee's CheerioCrawler.

2023-02-06 08:56 UTC, TheoVasilis commented on templates/manifest.json
> +            "description": "Standard and up to date template for developing with Crawlee's PuppeteerCrawler.",
Standard and up-to-date template for developing with Crawlee's PuppeteerCrawler.

2023-02-06 08:56 UTC, TheoVasilis commented on templates/manifest.json
> +            "description": "Standard and up to date template for developing with Crawlee's PlaywrightCrawler.",
Standard and up-to-date template for developing with Crawlee's PlaywrightCrawler.

2023-02-06 09:46 UTC, jbartadev approved these changes
Nice! Looks good to me. Thanks, guys!

2023-02-06 09:47 UTC, jbartadev commented
@PerVillalva Just a note: Please do not merge it yet as it could break some of the current logic of the templates in the console (the new version is in progress)

2023-02-06 09:55 UTC, PerVillalva commented
@jbartadev Alright, I will leave the decision to merge up to you then. Just ping me if you need anything else 🤝

2023-02-06 10:00 UTC, TheoVasilis approved these changes

2023-02-06 10:14 UTC, HonzaTuron commented
> @PerVillalva Just a note: Please do not merge it yet as it could break some of the current logic of the templates in the console (the new version is in progress)

@jbartadev New json seems to be backward-compatible with the old one (just added fields, right @PerVillalva?)

2023-02-06 10:37 UTC, jbartadev commented
> > @PerVillalva Just a note: Please do not merge it yet as it could break some of the current logic of the templates in the console (the new version is in progress)
> 
> @jbartadev New json seems to be backward-compatible with the old one (just added fields, right @PerVillalva?)

Yes it is in a way @HonzaTuron - but as you can see we're parsing the description to get the template title in the console and in this PR we added `title` field and remove the prefix from the `description` so the current logic wouldn't work properly. Make sense?

See 
<img width="286" alt="Snímek obrazovky 2023-02-06 v 11 34 37" src="https://user-images.githubusercontent.com/45016873/216949695-cc258416-ca12-4f6e-a10c-c5f52ac24c17.png">

2023-02-15 12:41 UTC, HonzaTuron commented
Please do not remove this branch after merging as production console mistakenly pointing to this branch. But feel free to merge. Thanks!

2023-02-16 15:08 UTC, merged