feat: add beautiful soup readme
apify/actor-templates pull request #160
Opened 2023-06-27 07:13 UTC by HonzaTuron

Closes apify/apify-web#2674.

Extended readme for beautiful soup + requests template.

2023-06-27 10:34 UTC, nguyeda1 approved these changes

2023-08-01 09:21 UTC, jbartadev requested changes

2023-08-02 08:57 UTC, jbartadev approved these changes

2023-08-02 12:15 UTC, merged

2023-08-02 12:52 UTC, B4nan commented
cc @vdusek, you might have some comments on this