rewrite scrapy readme
apify/actor-templates pull request #170
Opened 2023-07-24 13:34 UTC by HonzaTuron

Closes apify/apify-web#2675

Fixing readme to match the other template

2023-07-25 11:36 UTC, fnesveda requested changes

2023-07-25 12:49 UTC, fnesveda approved these changes

2023-07-26 11:21 UTC, HonzaTuron commented on templates/python-scrapy/README.md
> +
Well I'm doing this similarly to other readmes to include only apify-related features :shrug:

2023-07-26 11:51 UTC, jbartadev commented on templates/python-scrapy/README.md
> +
@HonzaTuron We had the same discussion last time, [here](https://apify.com/templates/ts-start) we have Axios and Cheerio and [here](https://apify.com/templates/python-start) we have Beautiful Soup and Requests 😄 I don't think we should limit the feature list only to Apify related ones as we want to explain what is included so it's prepared to work with.

2023-07-26 12:03 UTC, HonzaTuron commented on templates/python-scrapy/README.md
> +
Added :)

2023-07-28 08:18 UTC, jbartadev approved these changes

2023-07-28 08:37 UTC, merged