feat: add Actor Standby templates
apify/actor-templates pull request #278
Opened 2024-07-09 14:16 UTC by jirimoravcik

This PR adds templates for Actor Standby.

2024-07-09 14:20 UTC, jirimoravcik commented
Converted to a draft as we need to add `usesStandbyMode` logic that would setup Standby for the Actors

2024-07-11 09:48 UTC, fnesveda requested changes
Looks good, two small notes

2024-07-11 09:48 UTC, fnesveda commented on templates/js-standby/README.md
> +## Included features
Let's link Actor Standby docs here too, same in the other templates

2024-07-11 09:48 UTC, fnesveda commented on templates/js-standby/.actor/actor.json
> +    "meta": {
Let's add the `usesStandbyMode` top level property as per discussion in Slack. Also to all the other templates.
```suggestion
    "usesStandbyMode": true,
    "meta": {
```

2024-07-15 12:41 UTC, drobnikj commented
Can I go for a review? It is in draft

2024-07-15 12:43 UTC, jirimoravcik commented
> @jirimoravcik Can I go for a review? It is in draft

go for it, corresponding API change in https://github.com/apify/apify-core/pull/16649

2024-07-16 13:53 UTC, drobnikj approved these changes
Looks good just a few minor stuff

2024-07-16 13:53 UTC, drobnikj commented on templates/js-standby/package.json
> +        "node": ">=18.0.0"
Is it necessary to have a node js version here? If so, I would put at least the v20 as a docker image.

2024-07-16 13:53 UTC, drobnikj commented on templates/ts-standby/package.json
> +        "node": ">=18.0.0"
maybe same here

2024-07-16 13:53 UTC, drobnikj commented on templates/ts-standby/package.json
> +    "description": "This is an example of an Apify actor.",
nit: little bit tune description about standby

2024-07-16 13:53 UTC, drobnikj commented on templates/js-standby/package.json
> +    "description": "This is a boilerplate of an Apify Actor.",
nit: little bit tune description about standby

2024-07-17 10:29 UTC, jirimoravcik commented
I'll finalize this after https://github.com/apify/apify-docs/pull/1096 is merged so it can be linked

2024-07-18 08:56 UTC, fnesveda approved these changes

2024-07-22 15:29 UTC, merged